### ISSUE TITLE
Замечания по программе Compare

### ISSUE THREAD

**Issue by alexey-malov** [hahahu91/oop#2]
```c++
bool Compare(char& FileName1, char& FileName2)
```

- [x] Аналогично CopyFile

**Comment by alexey-malov** [comment]
```
	bool isCompare = true;
```

- [ ] Для переменной больше подходит имя filesAreEqual, contentIsSame, contentAreEqual

**Comment by alexey-malov** [comment]
Файлы в приложенном архиве различаются, однако программа считает их одинаковыми
[b.zip](https://github.com/hahahu91/oop/files/2866647/b.zip)

- [ ] Добавить тест для проверки этой ситуации и исправить проблему

- [ ] Также в тестах добавить проверки на нечувствительность программы к порядку сравниваемых файлов.

**Comment by hahahu91** [comment]
!
