### ISSUE TITLE
Замечания по программе CalcBits

### ISSUE THREAD

**Issue by alexey-malov** [hahahu91/oop#3]
```c++
	int byte = 0;	
	try
	{
		byte = stoi(argv[1]);
		if (byte <= UINT8_MAX && byte >= 0)
		{
			cout << BitCount(byte) << endl;
		}
		else
		{
			cout << "Invalid argument\n"
				 << "Usage: calcbits.exe <positive number>\n";
		} 
	}
	catch (const std::invalid_argument& err)
	{
		cout << err.what();	
		return 1;
	}
	return 0;
```

- [x] Если передать число, выходящее за пределы байта, программа выйдет с нулевым кодом возврата, но сообщит об ошибке. Должен в этом случае возвращаться ненулевой код возврата. Доработать тесты соответствующим образом

**Comment by hahahu91** [comment]
добавил возврат с ненулевым значением тестом проверяющий крайние значения

**Comment by alexey-malov** [comment]
- [ ] При проверке недопустимых значений следует проверять значения вблизи границы. Как допустимые (0, 255) так и недопустимые (-1, 256).

**Comment by alexey-malov** [comment]
- [ ] Устранить дублирование кода вывода инструкции.

**Comment by hahahu91** [comment]
Добавил тесты на допустимые (0, 255) так и недопустимые (-1, 256) и код вывода инструкции
