### ISSUE TITLE
Замечания по программ Bin2Dec

### ISSUE THREAD

**Issue by alexey-malov** [hahahu91/oop#4]
```
1>c:\teaching\ips\2019\morozov\oop\lab1\bin2dec\bin2dec\bin2dec.cpp(21): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>bin2dec.vcxproj -> C:\teaching\ips\2019\morozov\oop\lab1\x64\Debug\bin2dec.exe
```
- [x] Программа должна компилироваться без предупреждений компилятора во всех конфигурациях и платформах.

```c++
	for (int i = str.length() - 1; i >= 0; i--)
```

- [x] Для хранения индексов и размера контейнеров STL следует использовать тип size_t. НО, прямо сейчас если вы замените на size_t, то программа будет работать неправильно

**Comment by alexey-malov** [comment]
- [ ] Нет нужды возводить в степень при помощи pow. Операции битового сдвига и так аналогичны умножению на соотв. степень двойки.

**Comment by alexey-malov** [comment]
- [ ] Выделить из main отдельную функцию для перевода строки из двоичной системы в десятичную.

**Comment by hahahu91** [comment]
сделал

**Comment by alexey-malov** [comment]
- [ ] Не нужно использовать substr и stoi. Достаточно сравнить код i-го символа с '0' или '1', а для перевода в число вычесть '0'

**Comment by alexey-malov** [comment]
- [ ] Не надо дублировать код проверки валидности. Пусть это делает BinToNumber

**Comment by alexey-malov** [comment]
- [ ] BinInStr2dec1 лучше назвать BinToNumber

**Comment by alexey-malov** [comment]
```c++
bool BinToNumber(const string& decInStr, long& Number)
{
	string str = decInStr;
	Number = 0;
```

- [ ] Number -> number
